-- CreateTable
CREATE TABLE `RestaurantSettings` (
    `id` INTEGER NOT NULL DEFAULT 1,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `restaurantName` VARCHAR(120) NOT NULL,
    `tagline` VARCHAR(200) NOT NULL DEFAULT '',
    `shortDescription` VARCHAR(500) NOT NULL DEFAULT '',
    `longDescription` TEXT NOT NULL,
    `logoUrl` VARCHAR(191) NOT NULL DEFAULT '',
    `faviconUrl` VARCHAR(191) NOT NULL DEFAULT '',
    `primaryPhone` VARCHAR(40) NOT NULL DEFAULT '',
    `secondaryPhone` VARCHAR(40) NOT NULL DEFAULT '',
    `whatsappNumber` VARCHAR(40) NOT NULL DEFAULT '',
    `email` VARCHAR(160) NOT NULL DEFAULT '',
    `businessHours` JSON NOT NULL,
    `socialMedia` JSON NOT NULL,
    `metaTitle` VARCHAR(200) NOT NULL DEFAULT '',
    `metaDescription` VARCHAR(400) NOT NULL DEFAULT '',
    `keywords` VARCHAR(400) NOT NULL DEFAULT '',
    `ogImageUrl` VARCHAR(191) NOT NULL DEFAULT '',
    `darkModeDefault` BOOLEAN NOT NULL DEFAULT false,
    `accentColor` VARCHAR(9) NOT NULL DEFAULT '#c9a227',
    `primaryColor` VARCHAR(9) NOT NULL DEFAULT '#1a1a1a',
    `secondaryColor` VARCHAR(9) NOT NULL DEFAULT '#f4f4f2',
    `mapsEmbedUrl` VARCHAR(191) NOT NULL DEFAULT '',
    `latitude` DOUBLE NOT NULL DEFAULT 0,
    `longitude` DOUBLE NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
