-- Seed the SiteSEO singleton (id = 1) with the values that match the original
-- static metadata, so the public site is unchanged until the owner edits the
-- SEO panel. INSERT IGNORE keeps this idempotent and safe on first deploy.
INSERT IGNORE INTO `SiteSEO` (
    `id`,
    `siteTitle`,
    `metaTitle`,
    `metaDescription`,
    `keywords`,
    `canonicalUrl`,
    `ogTitle`,
    `ogDescription`,
    `ogImage`,
    `twitterTitle`,
    `twitterDescription`,
    `twitterImage`,
    `googleAnalyticsId`,
    `googleTagManagerId`,
    `googleSiteVerification`,
    `facebookDomainVerification`,
    `robotsIndex`,
    `robotsFollow`,
    `createdAt`,
    `updatedAt`
) VALUES (
    1,
    'Killo''s Biriyani',
    'Killo''s Biriyani — Arabian Restaurant',
    'The taste of Arabia — dum-cooked over open fire, served with a touch of luxury. Open daily 10:00 AM – 12:00 AM.',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    TRUE,
    TRUE,
    CURRENT_TIMESTAMP(3),
    CURRENT_TIMESTAMP(3)
);
